server:
  port: 8687

spring:
  application:
    name: simple-test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.100.1.100:3306/zhuzhenjie?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: Root@123#

mqtt:
  broker: tcp://47.101.184.101:1883
  username: test
  password: test
  publisher:
    clientId: mqtt-publisher
    defaultTopic: /topic/default
  subscriber:
    clientId: ${random.value}
    defaultTopic: /topic/default

logging:
  level:
    org.example.simpletest.mapper: debug
